# Generated by Django 4.2.3 on 2023-07-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('manufacturer', '0003_manufacturer_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='owner',
            field=models.CharField(blank=True, choices=[('factory', 'Завод'), ('entrepreneur', 'Индивидуальный предприниматель'), ('seller', 'Торговая сеть')], default='draft', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='product',
            field=models.ManyToManyField(null=True, to='products.product'),
        ),
    ]
